-- Canonical setup now lives in:
-- supabase/migrations/20260717_create_reviews_and_visitors.sql
-- Run that complete migration in the Supabase SQL Editor. It configures reviews,
-- browser-level unique visitors, safe RPCs, and all public permissions together.
