-- Run once in the Supabase SQL editor used by this project.
-- Requests are written only by the server with the service-role key.

create table if not exists public.project_requests (
  id bigint generated by default as identity primary key,
  request_id text not null unique check (request_id ~ '^NXA-[0-9]{8}-[A-F0-9]{8}$'),
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  package_id text not null check (package_id in ('basic', 'business', 'complete')),
  estimated_min_jod numeric(10, 3) not null,
  estimated_max_jod numeric(10, 3) not null,
  selected_currency text not null,
  is_rush boolean not null default false,
  payload jsonb not null,
  submitted_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.project_requests enable row level security;

revoke all on table public.project_requests from anon, authenticated;
revoke all on sequence public.project_requests_id_seq from anon, authenticated;

create index if not exists project_requests_submitted_at_idx
  on public.project_requests (submitted_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'project-request-pdfs',
  'project-request-pdfs',
  false,
  5242880,
  array['application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- No public storage policy is created. The service-role server adapter owns upload access.
