create table if not exists public.website_visits (
  id bigint generated by default as identity primary key,
  visitor_hash text not null,
  visited_at timestamptz not null default now(),
  page text,
  user_agent text
);

create index if not exists website_visits_hash_date_idx
  on public.website_visits (visitor_hash, visited_at);

alter table public.website_visits enable row level security;

revoke all on table public.website_visits from anon, authenticated;
grant select, insert on table public.website_visits to service_role;

grant usage, select on sequence public.website_visits_id_seq to service_role;

notify pgrst, 'reload schema';
