/** Central controls for the surface-to-core cinematic journey. */
export const DEPTH_JOURNEY_CONFIG = {
  hero: {
    brightness: 1.2,
    contrast: 1.05,
    saturation: 1.08,
    desktopPin: 1.85,
    mobilePin: 1.42,
    desktopZoom: 1.1,
    mobileZoom: 1.055,
    desktopRise: -5,
    mobileRise: -2.5,
    zoomStart: 0.06,
    supportFadeStart: 0.16,
    headingFadeStart: 0.33,
    groundCrossing: 0.46,
    foundationReveal: 0.84,
  },
  sections: {
    automationPin: 4.1,
    intelligencePin: 4.1,
    coreDesktopHeight: "175svh",
  },
  cards: {
    brightness: 1.04,
    inactiveOpacity: 0,
    activeScale: 1.012,
    activeLift: -6,
    revealDistance: 26,
    visiblePerGroup: 1,
  },
  motion: {
    scrub: 0.58,
    deepParallax: 18,
    mobileParallax: 6,
    planeParallax: {
      background: 8,
      midground: 14,
      mobileScale: 0.25,
    },
    cardRevealDuration: 0.075,
    cardGroupStart: 0.12,
    cardGroupGap: 0.13,
    workflowDuration: 0.48,
    aiCoreRotation: 8,
    finalCoreBrightness: 1.1,
  },
  particles: {
    foundation: 8,
    automation: 8,
    intelligence: 10,
    core: 8,
    mobile: 2,
  },
} as const;
