import { motion } from "framer-motion";
import {
  Activity,
  Bot,
  CalendarClock,
  Dumbbell,
  Salad,
  Sparkles,
  Target,
  TrendingUp,
} from "lucide-react";
import { AnimatedCounter } from "@/components/landing/AnimatedCounter";
import { translations, useLanguage } from "@/i18n/translations";
import type { LucideIcon } from "lucide-react";
import type { ReactNode } from "react";

type FitCoachDemoProps = {
  tr: (typeof translations)["en"];
};

export function FitCoachDemo({ tr }: FitCoachDemoProps) {
  const { language, dir } = useLanguage();
  const labels = {
    en: {
      generated: "Generated by AI",
      goal: "Goal: Strength",
      progress: "Progress",
      days: "5 days",
    },
    ar: {
      generated: "تم إنشاؤه بالذكاء الاصطناعي",
      goal: "الهدف: القوة",
      progress: "التقدم",
      days: "5 أيام",
    },
    es: {
      generated: "Generado por IA",
      goal: "Objetivo: fuerza",
      progress: "Progreso",
      days: "5 días",
    },
  }[language as "en" | "ar" | "es"] || {
    generated: "Generated by AI",
    goal: "Goal: Strength",
    progress: "Progress",
    days: "5 days",
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 44, scale: 0.96 }}
      whileInView={{ opacity: 1, y: 0, scale: 1 }}
      viewport={{ once: true, amount: 0.35 }}
      transition={{ duration: 0.85, ease: [0.22, 1, 0.36, 1] }}
      className="relative min-w-0"
    >
      <div
        className="absolute -inset-6 rounded-[2rem] blur-3xl opacity-40"
        style={{ background: "var(--gradient-primary)" }}
      />
      <div className="relative overflow-hidden rounded-[2rem] border border-primary/30 bg-background/82 p-4 shadow-[0_30px_100px_oklch(0.05_0.04_265_/_0.75)] backdrop-blur-2xl sm:p-6 xl:p-7">
        <div className="mb-6 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <div className="h-2 w-2 rounded-full bg-red-400/70" />
            <div className="h-2 w-2 rounded-full bg-yellow-400/70" />
            <div className="h-2 w-2 rounded-full bg-green-400/70" />
          </div>
          <span className="text-[0.7rem] text-muted-foreground sm:text-xs">
            {tr.caseStudy.dashboardUrl}
          </span>
        </div>

        <div className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
          <div className="rounded-3xl border border-border/60 bg-card/35 p-5 sm:p-6">
            <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
              <div className="inline-flex min-h-8 items-center gap-2 rounded-full border border-cyan/35 bg-cyan/10 px-3 py-1 text-xs text-cyan">
                <Sparkles className="h-3.5 w-3.5" />
                {labels.generated}
              </div>
              <div className="min-h-8 rounded-full bg-primary/15 px-3 py-1 text-xs text-muted-foreground">
                <Target
                  className={`${dir === "rtl" ? "ml-1" : "mr-1"} inline h-3.5 w-3.5 text-cyan`}
                />
                {labels.goal}
              </div>
            </div>

            <div className="rounded-2xl border border-primary/25 bg-primary/10 p-5">
              <div className="mb-3 flex items-center gap-2 text-sm font-semibold">
                <Bot className="h-4 w-4 text-cyan" />
                AI Coach
              </div>
              <motion.p
                className="text-base leading-8 text-muted-foreground"
                initial={{ opacity: 0.25 }}
                whileInView={{ opacity: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.9, delay: 0.2 }}
              >
                {tr.caseStudy.coach}
              </motion.p>
            </div>

            <div className="mt-5 grid grid-cols-2 gap-4">
              <MiniMetric
                icon={Activity}
                label={labels.progress}
                value={<AnimatedCounter to={88} suffix="%" />}
              />
              <MiniMetric
                icon={CalendarClock}
                label={tr.caseStudy.features[4]}
                value={labels.days}
              />
            </div>
          </div>

          <div className="grid gap-5 md:grid-cols-[1.08fr_0.92fr]">
            <div className="rounded-3xl border border-border/60 bg-card/35 p-5 sm:p-6">
              <div className="flex items-start justify-between gap-4">
                <div className="min-w-0">
                  <div className="text-xs uppercase tracking-widest text-muted-foreground">
                    {tr.caseStudy.today}
                  </div>
                  <div className="mt-3 break-words font-display text-2xl font-bold leading-tight">
                    {tr.caseStudy.plan}
                  </div>
                </div>
                <div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-primary/20">
                  <Dumbbell className="h-5 w-5 text-cyan" />
                </div>
              </div>
              <div className="mt-6 space-y-3">
                {tr.caseStudy.workouts.slice(0, 3).map(([name, sets], index: number) => (
                  <motion.div
                    key={name}
                    initial={{ opacity: 0, x: dir === "rtl" ? 12 : -12 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.16 + index * 0.08 }}
                    className="flex min-h-14 items-center justify-between gap-4 rounded-2xl border border-border/50 bg-background/35 px-4 py-3 text-base"
                  >
                    <span className="min-w-0 break-words">{name}</span>
                    <span className="shrink-0 font-mono text-gradient">{sets}</span>
                  </motion.div>
                ))}
              </div>
            </div>

            <div className="grid gap-5">
              <div className="rounded-3xl border border-border/60 bg-card/35 p-5 sm:p-6">
                <div className="flex items-center gap-2 text-base font-semibold">
                  <Salad className="h-4 w-4 text-cyan" />
                  {tr.caseStudy.features[2]}
                </div>
                <div className="mt-4 text-3xl font-bold text-gradient">2,450 kcal</div>
                <div className="mt-4 h-2.5 overflow-hidden rounded-full bg-card">
                  <motion.div
                    className="h-full rounded-full"
                    style={{ background: "var(--gradient-primary)" }}
                    initial={{ width: "18%" }}
                    whileInView={{ width: "76%" }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.9 }}
                  />
                </div>
              </div>
              <div className="rounded-3xl border border-border/60 bg-card/35 p-5 sm:p-6">
                <div className="mb-4 flex items-center gap-2 text-base font-semibold">
                  <TrendingUp className="h-4 w-4 text-cyan" />
                  {labels.progress}
                </div>
                <div className="flex h-28 items-end gap-2">
                  {[32, 48, 42, 66, 78, 88].map((height, index) => (
                    <motion.div
                      key={height}
                      className="flex-1 rounded-md"
                      style={{ background: "var(--gradient-primary)" }}
                      initial={{ height: "12%" }}
                      whileInView={{ height: `${height}%` }}
                      viewport={{ once: true }}
                      transition={{ delay: index * 0.07 }}
                    />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function MiniMetric({
  icon: Icon,
  label,
  value,
}: {
  icon: LucideIcon;
  label: string;
  value: ReactNode;
}) {
  return (
    <div className="min-w-0 rounded-2xl border border-border/60 bg-background/35 p-4 sm:p-5">
      <Icon className="h-4 w-4 text-cyan" />
      <div className="mt-3 break-words text-sm leading-6 text-muted-foreground">{label}</div>
      <div className="mt-1 font-display text-2xl font-bold text-gradient">{value}</div>
    </div>
  );
}
