/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVisitorsRouteImport } from './routes/api/visitors'
import { Route as ApiProjectRequestsRouteImport } from './routes/api/project-requests'
import { Route as ApiExchangeRatesRouteImport } from './routes/api/exchange-rates'
import { Route as ApiCustomerReviewsRouteImport } from './routes/api/customer-reviews'

const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitorsRoute = ApiVisitorsRouteImport.update({
  id: '/api/visitors',
  path: '/api/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectRequestsRoute = ApiProjectRequestsRouteImport.update({
  id: '/api/project-requests',
  path: '/api/project-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExchangeRatesRoute = ApiExchangeRatesRouteImport.update({
  id: '/api/exchange-rates',
  path: '/api/exchange-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerReviewsRoute = ApiCustomerReviewsRouteImport.update({
  id: '/api/customer-reviews',
  path: '/api/customer-reviews',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/start-project': typeof StartProjectRoute
  '/api/customer-reviews': typeof ApiCustomerReviewsRoute
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/project-requests': typeof ApiProjectRequestsRoute
  '/api/visitors': typeof ApiVisitorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start-project': typeof StartProjectRoute
  '/api/customer-reviews': typeof ApiCustomerReviewsRoute
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/project-requests': typeof ApiProjectRequestsRoute
  '/api/visitors': typeof ApiVisitorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/start-project': typeof StartProjectRoute
  '/api/customer-reviews': typeof ApiCustomerReviewsRoute
  '/api/exchange-rates': typeof ApiExchangeRatesRoute
  '/api/project-requests': typeof ApiProjectRequestsRoute
  '/api/visitors': typeof ApiVisitorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/start-project'
    | '/api/customer-reviews'
    | '/api/exchange-rates'
    | '/api/project-requests'
    | '/api/visitors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/start-project'
    | '/api/customer-reviews'
    | '/api/exchange-rates'
    | '/api/project-requests'
    | '/api/visitors'
  id:
    | '__root__'
    | '/'
    | '/start-project'
    | '/api/customer-reviews'
    | '/api/exchange-rates'
    | '/api/project-requests'
    | '/api/visitors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StartProjectRoute: typeof StartProjectRoute
  ApiCustomerReviewsRoute: typeof ApiCustomerReviewsRoute
  ApiExchangeRatesRoute: typeof ApiExchangeRatesRoute
  ApiProjectRequestsRoute: typeof ApiProjectRequestsRoute
  ApiVisitorsRoute: typeof ApiVisitorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visitors': {
      id: '/api/visitors'
      path: '/api/visitors'
      fullPath: '/api/visitors'
      preLoaderRoute: typeof ApiVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project-requests': {
      id: '/api/project-requests'
      path: '/api/project-requests'
      fullPath: '/api/project-requests'
      preLoaderRoute: typeof ApiProjectRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exchange-rates': {
      id: '/api/exchange-rates'
      path: '/api/exchange-rates'
      fullPath: '/api/exchange-rates'
      preLoaderRoute: typeof ApiExchangeRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer-reviews': {
      id: '/api/customer-reviews'
      path: '/api/customer-reviews'
      fullPath: '/api/customer-reviews'
      preLoaderRoute: typeof ApiCustomerReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StartProjectRoute: StartProjectRoute,
  ApiCustomerReviewsRoute: ApiCustomerReviewsRoute,
  ApiExchangeRatesRoute: ApiExchangeRatesRoute,
  ApiProjectRequestsRoute: ApiProjectRequestsRoute,
  ApiVisitorsRoute: ApiVisitorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
