/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVisitorsRouteImport } from './routes/api/visitors'

const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitorsRoute = ApiVisitorsRouteImport.update({
  id: '/api/visitors',
  path: '/api/visitors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/start-project': typeof StartProjectRoute
  '/api/visitors': typeof ApiVisitorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start-project': typeof StartProjectRoute
  '/api/visitors': typeof ApiVisitorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/start-project': typeof StartProjectRoute
  '/api/visitors': typeof ApiVisitorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/start-project' | '/api/visitors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/start-project' | '/api/visitors'
  id: '__root__' | '/' | '/start-project' | '/api/visitors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StartProjectRoute: typeof StartProjectRoute
  ApiVisitorsRoute: typeof ApiVisitorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visitors': {
      id: '/api/visitors'
      path: '/api/visitors'
      fullPath: '/api/visitors'
      preLoaderRoute: typeof ApiVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StartProjectRoute: StartProjectRoute,
  ApiVisitorsRoute: ApiVisitorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
